export const mCategories = ["Text", "Zahlen", "Datum", "Datum/Uhrzeit", "Bedingungen", "NULL und Fehler", "Spalten", "Tabellen", "Filtern", "Gruppieren", "Listen", "Merge / Join", "Datentypen", "Hilfreiche Spezialfunktionen"] as const;
export type MEntry = { name: string; category: string; use: string; input: string; code: string; result: string; adapt: string; where: string; note?: string; source: string };
const entries: MEntry[] = [];
function add(category: string, name: string, use: string, input: string, code: string, result: string, adapt: string, note?: string, source?: string) {
  entries.push({ category, name, use, input, code, result, adapt, note, where: name.startsWith("Table.") ? "Formelleiste: als vollständigen Schritt mit führendem = eingeben; den vorherigen Schrittnamen ersetzen." : "Spalte hinzufügen → Benutzerdefinierte Spalte: nur diesen Ausdruck eingeben, ohne führendes =.", source: "https://learn.microsoft.com/en-us/powerquery-m/" + (source || name.toLowerCase().replaceAll(".", "-")) });
}
add("Text", "Text.Trim", "Äußere Leerzeichen entfernen, etwa vor einem Merge.", 'Ort = " Mannheim "', 'Text.Trim([Ort])', '"Mannheim"', "[Ort] durch deine Textspalte ersetzen, etwa [Geschäftsstelle].", "Leerzeichen innerhalb des Textes bleiben erhalten.");
add("Text", "Text.Clean", "Nicht druckbare Steuerzeichen aus Exporten entfernen.", 'Bezeichnung = "Nord" + Zeilenumbruch + "Team"', 'Text.Clean([Bezeichnung])', '"NordTeam"', "[Bezeichnung] durch die betroffene Textspalte ersetzen.", "Ein entfernter Zeilenumbruch wird nicht durch ein Leerzeichen ersetzt.");
add("Text", "Text.Upper", "Text in Großschreibung bringen und Schreibweisen für Vergleiche vereinheitlichen.", 'Ort = "mannheim"', 'Text.Upper([Ort], "de-DE")', '"MANNHEIM"', "[Ort] ersetzen; de-DE ist das Gebietsschema.");
add("Text", "Text.Lower", "Text, etwa Kontaktkennungen, in Kleinschreibung bringen.", 'Kontakt = "POSTFACH"', 'Text.Lower([Kontakt], "de-DE")', '"postfach"', "[Kontakt] durch deine Textspalte ersetzen.");
add("Text", "Text.Proper", "Lesbare Anfangsbuchstaben für einfache Namen bilden.", 'Name = "MAX MUSTERMANN"', 'Text.Proper([Name], "de-DE")', '"Max Mustermann"', "[Name] ersetzen.", "Abkürzungen und fachliche Eigenschreibweisen können dadurch falsch werden.");
add("Text", "Text.Replace", "Bekannte Textteile ersetzen.", 'Bezeichnung = "alt-01"', 'Text.Replace([Bezeichnung], "alt", "neu")', '"neu-01"', "Spalte, gesuchten Text alt und Ersatz neu anpassen.", "Groß-/Kleinschreibung beachten; ersetzt passende Teiltexte.");
add("Text", "Text.Contains", "Einen Textbestandteil für Klassifikation prüfen.", 'Text = "Giro Basis"', 'Text.Contains([Text], "Giro")', "true", "[Text] und Suchtext Giro ersetzen.", "Case-sensitive; null als Eingabe liefert null. Fehlende Texte vor einer if-Bedingung behandeln.");
add("Text", "Text.StartsWith", "Produkte anhand eines Präfixes erkennen.", 'Produkt = "Kredit Standard"', 'Text.StartsWith([Produkt], "Kredit")', "true", "[Produkt] und Präfix ersetzen.");
add("Text", "Text.EndsWith", "Dateinamen auf eine Endung prüfen.", 'Dateiname = "Bestand_2026-01.xlsx"', 'Text.EndsWith([Dateiname], ".xlsx")', "true", "Dateinamenspalte (beim Ordnerimport oft [Name]) und Endung anpassen.", "Großschreibung wie .XLSX gesondert berücksichtigen; im Ordnerimport möglichst Extension filtern.");
add("Text", "Text.BeforeDelimiter", "Den ersten Teil einer zusammengesetzten Kennung lesen.", 'Bezeichnung = "ABC-123"', 'Text.BeforeDelimiter([Bezeichnung], "-")', '"ABC"', "Spalte und Trennzeichen ersetzen.");
add("Text", "Text.AfterDelimiter", "Den Teil nach einem Trennzeichen lesen.", 'Bezeichnung = "ABC-123"', 'Text.AfterDelimiter([Bezeichnung], "-")', '"123"', "Spalte und Trennzeichen ersetzen; mehrere Trennzeichen vorher prüfen.");
add("Text", "Text.BetweenDelimiters", "Eine eingebettete Kennung extrahieren.", 'Bezeichnung = "Team [NORD] aktiv"', 'Text.BetweenDelimiters([Bezeichnung], "[", "]")', '"NORD"', "Spalte sowie öffnendes und schließendes Trennzeichen ersetzen.", "Fehlende Trennzeichen zunächst als Datenproblem prüfen.");
add("Text", "Text.Start", "Einen festen Textanfang auswählen.", 'PLZ = "68159"', 'Text.Start([PLZ], 2)', '"68"', "[PLZ] ersetzen; 2 ist die Anzahl der Zeichen.", "Postleitzahlen als Text laden.");
add("Text", "Text.End", "Die letzten Zeichen einer technischen Kennung lesen.", 'Kontonummer = "12345678" (synthetisch)', 'Text.End([Kontonummer], 4)', '"5678"', "Spalte und gewünschte Zeichenanzahl 4 ersetzen.", "Ein gekürzter Wert ist weder automatisch eindeutig noch anonymisiert.");
add("Text", "Text.Middle", "Einen Textausschnitt ab einer festen Position lesen.", 'Kennung = "ABC123XYZ"', 'Text.Middle([Kennung], 3, 3)', '"123"', "Spalte, Startposition und Länge ersetzen.", "Nullbasiert: Position 0 ist das erste Zeichen; 3 ist das vierte.");
add("Text", "Text.Length", "Länge einer Kennung plausibilisieren.", 'Kontonummer = "12345678"', 'Text.Length([Kontonummer])', "8", "[Kontonummer] durch deine Textspalte ersetzen.");
add("Text", "Text.Combine", "Textteile mit einem Trennzeichen verbinden.", 'Vorname = "Max", Nachname = "Mustermann"', 'Text.Combine({[Vorname], [Nachname]}, " ")', '"Max Mustermann"', "Spalten in der Liste und Leerzeichen als Trenner anpassen.", "null wird ignoriert; leere Texte sind etwas anderes.");
add("Text", "Text.PadStart", "Eine bekannte feste Kennungslänge herstellen.", 'Nummer = "12345"', 'Text.PadStart([Nummer], 8, "0")', '"00012345"', "Textspalte, Ziellänge 8 und Füllzeichen 0 anpassen.", "IDs möglichst bereits als Text laden. Verlorene Nullen lassen sich nur mit gesicherter Ziellänge rekonstruieren.");
add("Text", "Text.From", "Eine Zahl gezielt als Text weiterverarbeiten.", "Nummer = 12345", 'Text.From([Nummer], "de-DE")', '"12345"', "Spalte und Gebietsschema ersetzen.", "Früher verlorene führende Nullen kommen dabei nicht zurück.");
add("Zahlen", "Number.Round", "Beträge auf eine definierte Genauigkeit runden.", "Betrag = 123.4567", "Number.Round([Betrag], 2)", "123.46", "Spalte und Zahl der Nachkommastellen 2 anpassen.", "Standard bei exakter Mitte: zur geraden Zahl (ToEven). Eine fachlich andere Rundungsregel ausdrücklich festlegen.");
add("Zahlen", "Number.RoundDown", "Zur kleineren Zahl abrunden.", "Betrag = -1.2", "Number.RoundDown([Betrag], 0)", "-2", "Spalte und Nachkommastellen ersetzen.", "Bei negativen Werten bedeutet abrunden nicht Richtung null.");
add("Zahlen", "Number.RoundUp", "Zur größeren Zahl aufrunden.", "Betrag = -1.2", "Number.RoundUp([Betrag], 0)", "-1", "Spalte und Nachkommastellen ersetzen.");
add("Zahlen", "Number.Abs", "Abweichungen unabhängig vom Vorzeichen betrachten.", "Abweichung = -500", "Number.Abs([Abweichung])", "500", "[Abweichung] ersetzen.", "Vorzeichen nur entfernen, wenn die fachliche Bedeutung das erlaubt.");
add("Zahlen", "Number.FromText", "Deutsche Dezimalwerte aus Text lesen.", 'Wert = "1.234,56"', 'Number.FromText([Wert], "de-DE")', "1234.56 als Zahl", "[Wert] und Gebietsschema der Quelle ersetzen.", "M-Code verwendet den Punkt für Zahlenliterale; de-DE beschreibt hier das Format des eingelesenen Textes.");
add("Zahlen", "Number.IntegerDivide", "Vollständige Pakete aus einer Stückzahl ermitteln.", "Anzahl = 27", "Number.IntegerDivide([Anzahl], 10)", "2", "Spalte und Paketgröße 10 ersetzen.", "Paketgröße darf nicht 0 sein.");
add("Zahlen", "Number.Mod", "Restmengen oder zyklische Zuordnungen bestimmen.", "Anzahl = 27", "Number.Mod([Anzahl], 10)", "7", "Spalte und Divisor 10 ersetzen.");
add("Datum", "Date.From", "Datumsangaben aus Text oder DateTime vereinheitlichen.", 'DatumText = "23.09.2026"', 'Date.From([DatumText], "de-DE")', "23.09.2026 als Datum", "Spalte und Quellgebietsschema ersetzen.");
for (const [name, result, use] of [
  ["Year", "2026", "Jahr für eine Zuordnung extrahieren."], ["Month", "9", "Monatsnummer für Sortierung extrahieren."], ["Day", "23", "Tag im Monat ermitteln."], ["QuarterOfYear", "3", "Quartalsnummer 1 bis 4 ermitteln."],
  ["StartOfMonth", "01.09.2026", "Monatsbeginn als gemeinsamen Periodenschlüssel bilden."], ["EndOfMonth", "30.09.2026", "Monatsende (Monatsultimo) als Stichtag ableiten."], ["StartOfYear", "01.01.2026", "Jahresbeginn für eine Zeitraumgrenze bestimmen."], ["EndOfYear", "31.12.2026", "Jahresende für eine Zeitraumgrenze bestimmen."]
]) add("Datum", "Date." + name, use, "Datum = 23.09.2026 (Typ Datum)", `Date.${name}([Datum])`, result, "[Datum] durch deine Datumsspalte ersetzen.");
add("Datum", "Date.MonthName", "Einen lesbaren Monatsnamen anzeigen.", "Datum = 23.09.2026", 'Date.MonthName([Datum], "de-DE")', '"September"', "Datumsspalte und Sprache ersetzen.", "Monatsnamen nach Monatsnummer sortieren, nicht alphabetisch.");
for (const [name, count, result, use] of [["AddDays", "7", "30.09.2026", "Eine Tagesfrist berechnen."], ["AddMonths", "1", "23.10.2026", "Einen Monat versetzen."], ["AddYears", "1", "23.09.2027", "Ein Jahr versetzen."]]) add("Datum", "Date." + name, use, "Datum = 23.09.2026", `Date.${name}([Datum], ${count})`, result, "Datumsspalte und Abstand ersetzen; negative Werte gehen zurück.", "Kalendertage sind keine Bankarbeitstage. Monatsenden und Schaltjahre gesondert prüfen.");
add("Datum", "Date.DayOfWeek", "Wochentage stabil nummerieren.", "Datum = 23.09.2026 (Mittwoch)", "Date.DayOfWeek([Datum], Day.Monday)", "2", "Datumsspalte ersetzen; Day.Monday legt Montag als Wochenbeginn fest.", "Montag = 0, Sonntag = 6. Ohne expliziten Wochenbeginn kann das Gebietsschema maßgeblich sein.");
add("Datum", "Date.DayOfWeekName", "Den Wochentag lesbar ausgeben.", "Datum = 23.09.2026", 'Date.DayOfWeekName([Datum], "de-DE")', '"Mittwoch"', "Datumsspalte und Sprache ersetzen.");
add("Datum/Uhrzeit", "DateTime.Date", "Den Datumsteil eines Zeitstempels verwenden.", "Zeitpunkt = 23.09.2026 14:30:00", "DateTime.Date([Zeitpunkt])", "23.09.2026", "[Zeitpunkt] durch deine DateTime-Spalte ersetzen.");
add("Datum/Uhrzeit", "DateTime.Time", "Den Uhrzeitteil eines Zeitstempels verwenden.", "Zeitpunkt = 23.09.2026 14:30:00", "DateTime.Time([Zeitpunkt])", "14:30:00", "[Zeitpunkt] durch deine DateTime-Spalte ersetzen.");
add("Datum/Uhrzeit", "DateTime.LocalNow", "Den Zeitpunkt der Auswertung diagnostisch erfassen.", "Ausführung beispielhaft am 23.09.2026 um 14:30", "DateTime.LocalNow()", "Ein datetime zum tatsächlichen Ausführungszeitpunkt; kein fester Beispielwert", "Keine Spalte einzusetzen. Vorher prüfen, ob Ausführungszeit überhaupt die richtige Information ist.", "Desktop verwendet die lokale Systemzeit, Onlineausführung typischerweise UTC. Nicht als Ersatz für einen fachlichen Stichtag nutzen; auch kein ständig laufender Berichtstimer.");
add("Datum/Uhrzeit", "Duration.Days", "Abstand zweier Datumswerte in Tagen bestimmen.", "Startdatum = 01.09.2026, Enddatum = 10.09.2026", "Duration.Days([Enddatum] - [Startdatum])", "9", "Beide Datumsspalten ersetzen. Die Subtraktion erzeugt zuerst eine Duration.", "Liefert den Tagesanteil. Bei Uhrzeiten werden angebrochene Tage nicht als Dezimaltage ausgegeben.");
add("Datum/Uhrzeit", "Duration.TotalHours", "Gesamte Laufzeit über Tagesgrenzen in Stunden berechnen.", "Start = 01.09.2026 08:00, Ende = 02.09.2026 09:30", "Duration.TotalHours([Ende] - [Start])", "25.5", "Beide DateTime-Spalten ersetzen.");
add("Datum/Uhrzeit", "Duration.TotalMinutes", "Laufzeiten in Minuten vergleichen.", "Start = 01.09.2026 08:00, Ende = 01.09.2026 09:30", "Duration.TotalMinutes([Ende] - [Start])", "90", "Beide DateTime-Spalten ersetzen.");
add("Bedingungen", "if … then … else", "Eine oder mehrere fachliche Klassen bilden.", "Bestand = 25000", 'if [Bestand] > 100000 then "Hoch"\nelse if [Bestand] > 10000 then "Mittel"\nelse "Niedrig"', '"Mittel"', "[Bestand], Grenzwerte und Ergebnistexte ersetzen. Einfacher Fall: if [Bestand] > 0 then \"Aktiv\" else \"Inaktiv\".", "Jede if-Bedingung braucht ein else. Erste zutreffende Bedingung gewinnt; Grenzwerte exakt prüfen.", "m-spec-conditionals");
add("Bedingungen", "and / or", "Mehrere Bedingungen verknüpfen.", 'Bestand = 500, Status = "Aktiv", Produkt = "B"', 'if [Bestand] > 0 and [Status] = "Aktiv"\n   and ([Produkt] = "A" or [Produkt] = "B")\nthen "Relevant" else "Nicht relevant"', '"Relevant"', "Spalten, Grenzwert, erlaubte Produkte und Ergebnistexte ersetzen.", "and verlangt beide Bedingungen, or mindestens eine. Gemischte Logik mit Klammern deutlich machen.", "m-spec-operators");
add("NULL und Fehler", "null prüfen", "Fehlende Werte sichtbar kennzeichnen.", "Wert = null", 'if [Wert] = null then "Fehlt" else "Vorhanden"', '"Fehlt"', "Spalte und Ergebnistexte ersetzen.", "null ist weder 0 noch leerer Text. Nicht ohne fachliche Begründung ersetzen.", "m-spec-values");
add("NULL und Fehler", "try … otherwise", "Fehler abfangen und ungültige Textzahlen kontrolliert behandeln.", 'Wert = "100" oder "unbekannt"', 'try Number.FromText([Wert], "de-DE") otherwise null', "100 beziehungsweise null", "Spalte, Quellgebietsschema und fachlich erlaubten Ersatzwert anpassen.", "Ursache zuerst verstehen; Fehler separat zählen. try [Zähler] / [Nenner] otherwise null reicht bei Division durch 0 nicht: #infinity und #nan sind mögliche Zahlenwerte. Vorher Nenner = null oder Nenner = 0 prüfen.", "m-spec-error-handling");
add("Hilfreiche Spezialfunktionen", "Record.FieldOrDefault", "Ein optionales Feld aus einem Datensatz lesen.", 'Datensatz = [Produkt = "A"] ohne Feld Hinweis', 'Record.FieldOrDefault([Datensatz], "Hinweis", "Nicht geliefert")', '"Nicht geliefert"', "Record-Spalte, Feldname und Ersatzwert ersetzen.", "Ein vorhandenes Feld mit null bleibt null. Pflichtspalten nicht auf diese Weise unbemerkt ausblenden.");
const previous = '#"Vorheriger Schritt"';
function table(category: string, name: string, use: string, input: string, args: string, result: string, adapt: string, note?: string) {
  add(category, name, use, input, `${name}(${previous}, ${args})`, result, `#"Vorheriger Schritt" durch deinen tatsächlichen Schrittnamen ersetzen. ${adapt}`, note);
}
table("Filtern", "Table.SelectRows", "Nur relevante Zeilen behalten.", "Bestand: -10, 0, 100", "each [Bestand] > 0", "Eine Zeile: Bestand 100", "Spalte, Vergleich und Grenzwert anpassen.");
table("Spalten", "Table.SelectColumns", "Eine gezielte Spaltenauswahl behalten.", "Spalten: Kundennummer, Bestand, Kommentar", '{"Kundennummer", "Bestand"}', "Nur Kundennummer und Bestand bleiben", "Liste der zu behaltenden Spaltennamen ersetzen.");
table("Spalten", "Table.RemoveColumns", "Nicht benötigte Spalten entfernen.", "Spalten: Kundennummer, Bestand, Kommentar", '{"Kommentar"}', "Kundennummer und Bestand bleiben", "Liste der zu entfernenden Spaltennamen ersetzen.");
table("Spalten", "Table.RenameColumns", "Quellnamen für weitere Schritte verständlich benennen.", "Spalte Saldo mit Wert 100", '{{"Saldo", "Bestand"}}', "Spalte Bestand mit Wert 100", "Je Paar zuerst alten, dann neuen Namen eintragen.");
table("Datentypen", "Table.TransformColumnTypes", "IDs, Zahlen und Stichtage typisieren.", 'Kundennummer = "0012", Bestand = "1.234,56", Stichtag = "30.09.2026"', '{{"Kundennummer", type text}, {"Bestand", type number}, {"Stichtag", type date}}, "de-DE"', 'Text "0012", Zahl 1234.56, Datum 30.09.2026', "Spaltennamen, Typen und Quellgebietsschema ersetzen.", "Typen: type text, Int64.Type (Ganzzahl), type number, Currency.Type (feste Dezimalzahl mit vier Nachkommastellen), type date, type datetime, type time, type logical. Typwahl auf Präzision und fachliche Bedeutung abstimmen.");
table("Spalten", "Table.AddColumn", "Eine berechnete Spalte als ganzen Schritt ergänzen.", 'Ort = "mannheim"', '"Ort Groß", each Text.Upper([Ort]), type text', 'Zusatzspalte Ort Groß = "MANNHEIM"', "Neuen Spaltennamen, Ausdruck, Quellspalte und Ergebnistyp ersetzen.", "Im Dialog Benutzerdefinierte Spalte nur Text.Upper([Ort]) eingeben, nicht diesen Tabellenschritt.");
table("Spalten", "Table.ReplaceValue", "Einen exakt passenden Tabellenwert ersetzen.", 'Status: "A", "B", "AA"', '"A", "Aktiv", Replacer.ReplaceValue, {"Status"}', 'Status: "Aktiv", "B", "AA"', "Suchwert, Ersatzwert und Spaltenliste ersetzen.", "Replacer.ReplaceValue ersetzt vollständige Werte; Text.Replace ersetzt dagegen Teiltexte.");
table("Spalten", "Table.FillDown", "Gruppenbeschriftungen in schlecht strukturierten Exporten nach unten auffüllen.", 'Team: "Nord", null, "Süd", null', '{"Team"}', '"Nord", "Nord", "Süd", "Süd"', "Spaltenliste ersetzen; Reihenfolge vorher sichern.", "Füllt null, nicht automatisch leere Texte. Nicht über fachliche Gruppengrenzen hinweg auffüllen.");
table("Spalten", "Table.FillUp", "Eine erst am Ende stehende Gruppenbeschriftung nach oben übertragen.", 'Team: null, "Nord", null, "Süd"', '{"Team"}', '"Nord", "Nord", "Süd", "Süd"', "Spaltenliste ersetzen; Gruppengrenzen und Reihenfolge prüfen.");
table("Tabellen", "Table.Distinct", "Doppelte Schlüssel nach geklärter Granularität reduzieren.", 'Kundennummer: "K01", "K01", "K02"', '{"Kundennummer"}', 'Zwei Zeilen: "K01", "K02"', "Spaltenliste auf den fachlichen Schlüssel abstimmen.", "Bei weiteren unterschiedlichen Spalten ist nicht garantiert, welche Zeile erhalten bleibt. Nicht blind einen Monatsbestand je Kunde entfernen.");
table("Tabellen", "Table.Sort", "Eine explizite Verarbeitungsreihenfolge herstellen.", "Bestand: 10, 30, 20", '{{"Bestand", Order.Descending}}', "30, 20, 10", "Sortierspalte und Order.Descending/Order.Ascending ersetzen.", "Spätere Schritte können die Reihenfolge wieder verändern.");
table("Gruppieren", "Table.Group", "Bestände innerhalb eines Stichtags je Produkt verdichten.", "Alle Zeilen am 30.09.2026: A/10, A/20, B/5", '{"Stichtag", "Produkt"}, {{"Bestand gesamt", each List.Sum([Bestand]), type number}}', "30.09.2026: A/30, B/5", "Gruppierungsschlüssel, Ergebnisname, Wertspalte und Aggregation ersetzen.", "Stichtag im Schlüssel behalten; Bestände verschiedener Monate nicht einfach summieren.");
add("Tabellen", "Table.Combine", "Gleich strukturierte Tabellen untereinander anhängen (Append).", "Januar: K01/10; Februar: K02/20", "Table.Combine({Januar, Februar})", "Zwei Zeilen: K01/10 und K02/20", "Januar und Februar durch bestehende Abfragen ersetzen, bei Leerzeichen etwa #\"Bestand Januar\".", "Spalten werden über Namen zugeordnet. Fehlende Spalten können null erzeugen; Schema prüfen.");
table("Merge / Join", "Table.NestedJoin", "Stammdaten über einen Schlüssel zuordnen (Merge).", "Bestand: K01/10, K02/20; Stammdaten: K01/Nord", '{"Kundennummer"}, Stammdaten, {"Kundennummer"}, "Treffer", JoinKind.LeftOuter', "Zwei Zeilen mit verschachtelter Tabelle Treffer; K01 hat einen Treffer, K02 keinen", "Linken/rechten Schlüssel, Abfrage Stammdaten, Ergebnisname und Join-Art ersetzen.", "Üblicherweise über Abfragen zusammenführen erzeugen. Treffer anschließend am Doppelpfeil erweitern; mehrere Treffer vervielfachen Zeilen. Datentypen und Eindeutigkeit prüfen.");
table("Hilfreiche Spezialfunktionen", "Table.AddIndexColumn", "Eine technische Zeilennummer für Transformationslogik ergänzen.", 'Zeilen in festgelegter Reihenfolge: "Nord", "Süd"', '"Index", 1, 1, Int64.Type', "Index 1 für Nord, 2 für Süd", "Spaltenname, Startwert und Schrittweite anpassen.", "UI: Spalte hinzufügen → Indexspalte. Die aktuelle Reihenfolge zuvor festlegen; eine neue Lieferung kann die Nummern ändern. Kein automatisch stabiler fachlicher Schlüssel.");
for (const [name, result, use] of [["Sum", "60", "Werte einer Liste summieren."], ["Average", "20", "Das arithmetische Mittel bestimmen."], ["Min", "10", "Den kleinsten Wert finden."], ["Max", "30", "Den größten Wert finden."], ["Count", "3", "Elemente einer Liste zählen."]]) add("Listen", "List." + name, use, "Werte = {10, 20, 30}", `List.${name}([Werte])`, result, "[Werte] ist hier eine Spalte mit Listenwerten, keine einzelne Zahl. In einer Gruppierung z. B. [Bestand] als Spaltenliste verwenden.", name === "Count" ? "List.Count zählt auch null-Elemente; nicht mit einer Anzahl gefüllter Werte verwechseln." : "Fehlende Werte und leere Listen fachlich gesondert prüfen.");
add("Listen", "List.Distinct", "Eine Liste auf unterschiedliche Werte reduzieren.", 'Kategorien = {"A", "A", "B"}', "List.Distinct([Kategorien])", '{"A", "B"}', "[Kategorien] durch eine Listenspalte ersetzen.", "Liefert eine Liste, keine Tabelle.");
add("Listen", "List.Contains", "Eine Kategorie gegen mehrere erlaubte Werte prüfen.", 'Kategorie = "B"', 'List.Contains({"A", "B", "C"}, [Kategorie])', "true", "Erlaubte Werte in geschweiften Klammern und Kategorie-Spalte ersetzen.");
export const mEntries: readonly MEntry[] = entries;
const normalize = (text: string) => text.toLocaleLowerCase("de-DE").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9äöüß]+/g, " ").trim();
export function findMEntries(query: string, category = "") {
  const words = normalize(query).split(/\s+/).filter(Boolean);
  return mEntries.filter(entry => (!category || entry.category === category) && words.every(word => normalize([entry.name, entry.category, entry.use, entry.code, entry.adapt, entry.note].join(" ")).includes(word)));
}
